### ISSUE TITLE
Capability to Delete Files

### ISSUE THREAD

**Issue by EstebanBorai** [whizzes/imagekit#3]
Provide capability to delete files from storage.

Refer: https://docs.imagekit.io/api-reference/media-api/delete-file

**Comment by alejandro0619** [comment]
> Provide capability to delete files from storage.
> 
> Refer: https://docs.imagekit.io/api-reference/media-api/delete-file

Already done right?

**Comment by EstebanBorai** [comment]
> > Provide capability to delete files from storage.
> > Refer: https://docs.imagekit.io/api-reference/media-api/delete-file
> 
> Already done right?

Yeah! It was introduced here: 53517fb, thanks for pointing it out!
