### ISSUE TITLE
Use `thiserror` for error reporting

### ISSUE THREAD

**Issue by EstebanBorai** [whizzes/imagekit#6]
It would be nice to abstract documentation error codes into an error enum.
We could use https://crates.io/crates/thiserror for this task.

**Comment by alejandro0619** [comment]
I'll start working on this right away

**Comment by EstebanBorai** [comment]
> I'll start working on this right away

Hi @alejandro0619! Any news on this?

**Comment by alejandro0619** [comment]
> > I'll start working on this right away
> 
> Hi @alejandro0619! Any news on this?

Hello! Yes, sorry for being out for a while. University has been stressing haha. In between today and tomorrow I'll try to submit a PR and get feedback

**Comment by alejandro0619** [comment]
I've added the custom error enum. And I've implemented it, but I've been unable to run successfully the tests. The error being shown is: 
```
---- tests::uploads_then_deletes_file stdout ----
thread 'tests::uploads_then_deletes_file' panicked at 'called `Result::unwrap()` on an `Err` value: HttpClientError(reqwest::Error { kind: Decode, source: Error("missing field `fileId`", line: 1, column: 115) })', src/lib.rs:30:57 
```
Seem like there's an error while deserializing the code with serde, but I haven't found (yet) the reason behind it. The code is in this [branch](https://github.com/alejandro0619/imagekit/tree/feat-custom-error). May this be related to a change in the response structure?

**Comment by EstebanBorai** [comment]
Hi @alejandro0619! 

Yes in is! The error is related to decoding, I suggest logging the serialized response.

I also noticed that the version of reqwest is out of date in your branch, can you update? Theres new patches available.

**Comment by alejandro0619** [comment]
> Hi @alejandro0619! 
> 
> Yes in is! The error is related to decoding, I suggest logging the serialized response.

Okay perfect, I'll work on it and report to you the progress. Thanks @EstebanBorai
