### ISSUE TITLE
feat: add basic image resizing url transformation

### ISSUE THREAD

**Issue by sajuthankappan** [whizzes/imagekit#9]
Created pull request to add basic image resizing url transformation. Please let me know your thoughts.

https://github.com/whizzes/imagekit/pull/8

Note: I'm not a seasoned rust developer. So, appreicate inputs for any improvements :)

**Comment by EstebanBorai** [comment]
Hi @sajuthankappan thanks for taking the time!

I just saw your PR and it looks good, the crate is not very mature as of today and needs more iterations to add support as you just did. Feel free to keep comming!

**Comment by sajuthankappan** [comment]
> Hi @sajuthankappan thanks for taking the time!
> 
> I just saw your PR and it looks good, the crate is not very mature as of today and needs more iterations to add support as you just did. Feel free to keep comming!

Thanks @EstebanBorai  for your encouraging words. Happy to contribute my first bit here. Hoping to make more contributions in the coming days/future..

**Comment by sajuthankappan** [comment]
As the PR is merged, marking this as closed..
